services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    restart: always

  products-ms:
      build: ./products-ms
      ports:
        - "3001:3001"
      volumes:
        - ./products-ms:/usr/src/app
        - /usr/src/app/node_modules
      command: npm run start:dev
      environment:
        - PORT=3001
        - NATS_SERVERS=nats://nats-server:4222
        - DATABASE_URL=file:./dev.db
      restart: always

  # Orders database
  orders-db:
    image: postgres:17
    container_name: orders_database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./orders-ms/postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  #Order MicroService
  orders-ms:
    depends_on:
      orders-db:
        condition: service_healthy
        restart: true
    build: ./orders-ms
    ports:
      - ${ORDERS_APP_PORT}:3002
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${ORDERS_APP_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@orders-db:5432/${DB_NAME}?schema=public
    restart: always
